# Generated by Django 2.2.12 on 2021-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('RelationShip', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
    ]
